.dockerignore, .gitignore, Dockerfile, Pipfile, Pipfile.lock, README.md, bin/server.sh, development.yml, docker-compose.testing.yml, docker-compose.yml, jupyter.yml, production.yml, recommender/__init__.py, recommender/api/__init__.py, recommender/api/endpoints/database_dumps.py, recommender/api/endpoints/recommendations.py, recommender/tasks/db.py, recommender/tasks/example.py, settings.py, tests/endpoints/test_database_dumps.py, uwsgi.ini, worker.py
https://medium.com/faun/using-nginx-uwsgi-and-docker-to-deploy-your-flask-application-db89da5894d2
Closes #7
=> [#7] Create docker-compose image for flask application

Pipfile, Pipfile.lock, recommender/__init__.py, training_and_inferention_example.ipynb
=> [HOTFIX] pre-agent-hotfix

Pipfile.lock, recommender/api/schemas/recommendation.py, recommender/engine/pre_agent/pre_agent.py, recommender/models/recommendation.py, recommender/models/service.py, recommender/models/state.py, recommender/services/deserializer.py, recommender/services/fts.py, tests/factories/recommendation.py, tests/services/test_fts.py
=> [#19] Mongo FTS integration

recommender/api/schemas/recommendation.py, recommender/api/schemas/user_action.py, recommender/engine/pre_agent/pre_agent.py, recommender/models/recommendation.py, recommender/models/user_action.py, recommender/services/deserializer.py, recommender/services/sarses_generator.py, tests/factories/recommendation.py, tests/factories/user_action/user_action.py, tests/services/test_sarses_generator.py, training_and_inferention_example.ipynb
=> [#43] Remove logged_user field

recommender/api/schemas/recommendation.py, recommender/models/search_data.py, recommender/services/deserializer.py
API adjustment. Changed category id to the list of categories ids in the recommendation request json.
=> [cyfronet-fid/marketplace#1898] Refactor category to categories in API

recommender/engine/base_agent_recommender.py, recommender/engine/pre_agent/models/autoencoders.py, recommender/engine/rl_agent/action_selector.py, recommender/engine/rl_agent/architecture_and_interfaces.py, recommender/engine/rl_agent/datasets/replay_buffer_generator.py, recommender/engine/rl_agent/models/actor_model.py, recommender/engine/rl_agent/models/critic_model.py, recommender/engine/rl_agent/models/history_embedder.py, recommender/engine/rl_agent/preprocessing/action_embedder.py, recommender/engine/rl_agent/preprocessing/filters_embedder.py, recommender/engine/rl_agent/preprocessing/searchphrase_embedder.py, recommender/engine/rl_agent/preprocessing/state_embedder.py, recommender/engine/rl_agent/rl_agent.py, recommender/engine/rl_agent/training/common.py
=> RL agent architecture

recommender/engine/rl_agent/preprocessing/filters_embedder.py
Implementation of the Filters Embedder.
=> [#54] Filters Embedder

Pipfile, Pipfile.lock, recommender/engine/rl_agent/preprocessing/searchphrase_embedder.py
Implementation of the Search Phrase Embedder.
=> [#55] Search phrase Embedder

Pipfile, Pipfile.lock, recommender/engine/rl_agent/preprocessing/filters_embedder.py, recommender/engine/rl_agent/preprocessing/searchphrase_embedder.py, recommender/engine/rl_agent/preprocessing/state_embedder.py, recommender/models/sars.py, recommender/models/state.py, recommender/services/sarses_generator.py, tests/factories/search_data.py, tests/factories/state.py, tests/test_embedders.py
Implementation of the State Embedder.
=> [#53] State Embedder

recommender/engine/rl_agent/models/history_embedder.py, tests/test_history_embedder.py
=>  [#58] Implement History Embedder

recommender/api/endpoints/recommendations.py, recommender/engine/pre_agent/pre_agent.py, recommender/errors.py, recommender/models/service.py, recommender/services/fts.py, tests/factories/marketplace/service.py, tests/test_pre_agent.py
This PR solves issue cyfronet-fid/marketplace#1998 on the recommender side. Should be considered together with cyfronet-fid/marketplace#2023 (that solves this issue on the marketplace side).
What have been done:
- filter unpublished services from recommendation
- improve response generating time from ~800ms to ~ 580ms
- improve missing services handling
=> [#1998] Don't recommend unpublished services

Pipfile, recommender/services/sarses_generator.py, recommender/services/services_history_generator.py, recommender/utils.py, tests/services/test_services_history_generator.py
Implementation of the Services History Generator. Closes #73
=> [#73] Services History Generator

recommender/engine/base_agent_recommender.py, recommender/engine/pre_agent/pre_agent.py, tests/test_pre_agent.py
Implemented BaseAgentRecommender class and adjusted PreAgentRecommender to it.
=> [#60] Base Agent Recommender

recommender/engine/rl_agent/action_selector.py, recommender/engine/rl_agent/rl_agent.py, recommender/errors.py
Implementation of the RL Agent Recommender. Closes #61
=> [#61] RL Agent Recommender

Pipfile, recommender/api/endpoints/recommendations.py, recommender/engine/base_agent_recommender.py, recommender/engine/pre_agent/pre_agent.py, recommender/engine/rl_agent/action_selector.py, recommender/engine/rl_agent/rl_agent.py, recommender/errors.py, recommender/services/sarses_generator.py, recommender/services/services_history_generator.py, recommender/utils.py, tests/services/test_services_history_generator.py, tests/test_pre_agent.py
Implemented:
- Services History Generator (Closes #80)
- Base Agent Recommender (Closes #78) 
- RL Agent Recommender (Closes #81)
=> [#67] Agent

recommender/services/synthetic_dataset_generator.py, tests/test_synthetic_dataset_generator.py
Also added some important utility methods and tests
=> [#65] Implement User Interest Evaluation

recommender/engine/reward_mapping.py, recommender/services/sarses_generator.py, resources/transition_adj_matrix.csv, resources/transition_rewards.csv, tests/test_reward_mapping.py
Additional changes:
- added workaround for non-logged user when generating SARSes.
=> [#63] Reward mapping

recommender/engine/reward_mapping.py, recommender/services/sarses_generator.py, recommender/services/synthetic_dataset_generator.py, resources/transition_adj_matrix.csv, resources/transition_rewards.csv, tests/test_reward_mapping.py, tests/test_synthetic_dataset_generator.py
Partially Implement synthetic SARSes generator.
=> [#64] Synthetic SARSes generator partial implementation

recommender/engine/rl_agent/action_selector.py, recommender/services/fts.py, tests/services/test_fts.py, tests/test_action_selector.py
=> [#59] Implement ActionSelector

recommender/api/endpoints/recommendations.py, recommender/engine/base_agent_recommender.py, recommender/engine/pre_agent/pre_agent.py, recommender/services/fts.py, tests/test_pre_agent.py
Fix of bugs associated with fill_candidate_services function:
=> [#96] fill_candidate_services bugs

recommender/engine/agents/rl_agent/models/action_embedder.py, recommender/engine/agents/rl_agent/models/actor.py, recommender/engine/agents/rl_agent/models/critic.py, recommender/engine/agents/rl_agent/preprocessing/action_encoder.py, tests/test_action_encoder.py, tests/test_critic_model.py, tests/test_embedders.py
Implementation of:
- ActionEncoder
- ActionEmbedder
- Critic
=> [#89, #90] Action Encoder, Action Embedder and Critic

README.md, recommender/api/__init__.py, recommender/api/endpoints/reload.py, recommender/api/endpoints/training.py, recommender/api/endpoints/update.py, recommender/engine/agents/pre_agent/pre_agent.py, recommender/engine/agents/rl_agent/rl_agent.py, recommender/tasks/neural_networks.py, settings.py
=> [#110, #68] Update endpoint, model reloading

recommender/api/schemas/recommendation.py, recommender/utils.py
=> [#111] Smart Examples in Swagger

recommender/engine/agents/base_agent.py, recommender/engine/agents/pre_agent/pre_agent.py, recommender/engine/agents/rl_agent/rl_agent.py, tests/endpoints/test_recommendations.py, tests/test_pre_agent.py
=> [#121] Move _load_models() to init in agents classes

recommender/engine/agents/pre_agent/training/common.py, recommender/engine/agents/rl_agent/datasets/replay_buffer.py, recommender/engine/agents/rl_agent/training/common.py, recommender/engine/agents/rl_agent/utils.py, recommender/services/sarses_generator.py, tests/factories/search_data.py, tests/test_replay_buffer.py, tests/test_rl_agent.py
=> [#124] Refactoring

README.md
=> [#130] Update training section in the Readme.md

Pipfile, Pipfile.lock, recommender/services/synthetic_dataset/env.py, tests/factories/marketplace/user.py, tests/services/synthetic_dataset/test_env.py
=> [#135] Add Synthetic Marketplace gym.Env

recommender/engine/agents/rl_agent/utils.py, tests/test_sars_encoder.py, tests/test_utils.py
=> [#180] Fix SARS Encoder test

tests/services/test_mp_dump.py, tests/tasks/test_db.py
=> [#182] Fix Load DB Dump test

tests/test_search_data_encoder.py
=> [#173] Fix search data encoder tests

README.md, recommender/api/endpoints/recommendations.py
=> [#255] Add ENV variable, which points to default recommendation algorithm

recommender/engines/autoencoders/ml_components/autoencoder.py, recommender/engines/autoencoders/training/model_training_step.py, recommender/pipeline_configs.py, tests/engines/conftest.py, tests/unit/engines/autoencoders/ml_components/test_autoencoder.py
=> [#234] Add the ability to change the sizes and number of layers in AE

CHANGELOG.md, recommender/engines/autoencoders/ml_components/autoencoder.py, recommender/engines/base/base_neural_network.py, recommender/engines/ncf/ml_components/content_mlp.py, recommender/engines/ncf/ml_components/mlp.py, recommender/engines/ncf/ml_components/neural_collaborative_filtering.py, recommender/engines/rl/ml_components/actor.py, recommender/engines/rl/ml_components/critic.py, recommender/engines/rl/ml_components/history_embedder.py
=> [#191] Refactor neural networks layers definitions

CHANGELOG.md, recommender/engines/autoencoders/training/data_preparation_step.py, recommender/engines/autoencoders/training/data_validation_step.py, recommender/errors.py, recommender/pipeline_configs.py, tests/conftest.py, tests/unit/engines/autoencoders/conftest.py, tests/unit/engines/autoencoders/training/test_data_preparation_step.py, tests/unit/engines/autoencoders/training/test_data_validation_step.py
=> [#287] AE split validation in data preparation step

CHANGELOG.md, recommender/commands/db.py, recommender/errors.py, tests/factories/populate_database.py
=> [#298] Fix: flask db seed command

README.md
=> [#295] Enhance the language of the README

CHANGELOG.md, recommender/errors.py, tests/factories/marketplace/faker_seeds/utils/dumpers.py
=> [#289] Using flask seed_faker command on an empty database

.run/Flask (app.py).run.xml, recommender/__init__.py, recommender/api/schemas/recommendation.py, recommender/models/recommendation.py, recommender/services/deserializer.py, recommender/services/metrics.py, tests/endpoints/test_recommendations.py, tests/factories/recommendation.py
Closes #281
There is `flask hitrate` comand with arguments: `engine_version` and `panel_id`. Recommendations that match these parameters are used to calculate two numbers:
- sum of clicks on recommendation panel
- sum of clicks on something else than recommendation panel when on recommendation panel page.
- there could be much more metrics
- metrics CLI (for now there is only one command)
=> [#281] Higher level metric computation (POC)

CHANGELOG.md, recommender/engines/autoencoders/training/data_preparation_step.py, tests/unit/engines/autoencoders/training/test_data_preparation_step.py
=> [#310] Fix: AE data preparation step - create_details - returns incorrect data

CHANGELOG.md, recommender/engines/rl/ml_components/sarses_generator.py, recommender/engines/rl/training/data_extraction_step/data_extraction_step.py, recommender/tasks.py, tests/conftest.py, tests/services/test_sarses_generator.py
=> [#314] fix multiprocessing in celery

CHANGELOG.md, Pipfile, Pipfile.lock, README.md, jms/connector.py, tests/unit/jms/conftest.py, tests/unit/jms/test_connector.py
=> [#320] JMS integration

CHANGELOG.md, recommender/api/endpoints/recommendations.py, recommender/services/rec_engine_selector.py, tests/services/test_rec_engine_selector.py
=> [#333] If requested recommendation engine does not exist try to use other model

CHANGELOG.md, README.md
=> [#330] Flask train, db and docs in the README

CHANGELOG.md, recommender/__init__.py, recommender/commands/db.py, recommender/models/__init__.py, recommender/services/drop_ml_models.py, recommender/services/mp_dump.py, recommender/tasks.py, tests/services/test_drop_ml_models.py
=> [#341] Deleting models from m_l_component collection

CHANGELOG.md, README.md, recommender/__init__.py, recommender/commands/train.py, recommender/pipeline_configs.py, recommender/tasks.py
closes #303
v2 configuration was not removed from the tests because we intend to preserve this feature in general, thus it's worth testing.
=> [#303] v2 configuration of RL pipeline removed

CHANGELOG.md, recommender/__init__.py, recommender/commands/train.py
=> [#352] Add drop_ml_models to flask train all

CHANGELOG.md, recommender/commands/train.py, recommender/engines/autoencoders/inference/embedding_component.py, recommender/engines/autoencoders/ml_components/embedder.py, recommender/engines/autoencoders/ml_components/normalizer.py
closes #356
Embedding looks like this right now:
All logs may be disabled using (`verbose=False`)
=> [#356] tqdm and logging in embedding pipeline

CHANGELOG.md, tests/conftest.py, tests/endpoints/conftest.py, tests/engines/autoencoders/conftest.py, tests/engines/autoencoders/inference/test_embedding_component.py, tests/engines/ncf/conftest.py, tests/engines/rl/conftest.py, tests/migrate/conftest.py, tests/services/conftest.py, tests/services/test_drop_ml_models.py, tests/services/test_rec_engine_selector.py
=> [#347] Cleaning up fixtures in the main conftest

CHANGELOG.md, README.md, recommender/__init__.py, recommender/commands/__init__.py, recommender/commands/db.py, recommender/commands/seed.py
=> [#366] Split db commands

CHANGELOG.md, Pipfile, Pipfile.lock, recommender/api/endpoints/recommendations.py, recommender/api/endpoints/update.py, recommender/api/endpoints/user_actions.py, recommender/engines/autoencoders/training/data_preparation_step.py, recommender/engines/base/base_inference_component.py, recommender/engines/ncf/inference/ncf_inference_component.py, recommender/engines/ncf/ml_components/content_mlp.py, recommender/engines/ncf/ml_components/mlp.py, recommender/engines/rl/inference/rl_inference_component.py, recommender/engines/rl/ml_components/service_selector.py, recommender/errors.py
=> [#378] Fix dependabot alerts

recommender/api/schemas/database_dump/database_dump.py, recommender/api/schemas/database_dump/project.py, recommender/models/__init__.py, recommender/models/project.py, tests/endpoints/conftest.py
Added project model and schema validator
=> [#2761] Add project to recommender dump

CHANGELOG.md, recommender/api/endpoints/recommendations.py, recommender/api/schemas/recommendation.py, recommender/errors.py, recommender/models/__init__.py, recommender/services/provide_service_ctx.py, tests/services/test_provide_service_ctx.py
=> [#392] Adjust /recommednations endpoint for the User Dashboard purpose

CHANGELOG.md
=> [#348] Data Ingestion Redesign

recommender/api/schemas/common.py, recommender/api/schemas/recommendation.py, recommender/api/schemas/user_action.py, recommender/models/recommendation.py, recommender/models/user_action.py, recommender/services/deserializer.py, tests/endpoints/conftest.py, tests/endpoints/test_user_actions.py, tests/services/conftest.py, tests/services/test_deserializer.py
=> [#396] Add client_id to the recommendation and user_action request

CHANGELOG.md, recommender/api/endpoints/recommendations.py
=> [#407] Get proper engine_version to the recommendations response

tests/jms/test_jms.py, tests/tasks/test_send_recommendations_to_databus.py
Forgot to commit test publish recommendations tests - here they are
=> [AdHoc] Test publish recommendations to databus

CHANGELOG.md, recommender/api/endpoints/user_actions.py, recommender/api/schemas/user_action.py, recommender/services/deserializer.py, recommender/services/mp_dump.py, recommender/types.py, tests/endpoints/test_user_actions.py, tests/factories/requests/user_actions.py, tests/services/conftest.py, tests/services/test_deserializer.py
=> [#404] Adjust user actions

CHANGELOG.md, README.md, recommender/api/__init__.py, recommender/api/endpoints/health_check.py, recommender/engines/random/inference/random_inference_component.py, recommender/services/engine_selector.py, recommender/services/health_check.py, recommender/tasks.py, tests/services/test_engine_selector.py
=> [#411] Implement deep health check

CHANGELOG.md, README.md, recommender/engines/base/base_inference_component.py
=> [#418] Better exception handling for finding user in the db

recommender/errors.py, recommender/services/provide_service_ctx.py, tests/services/test_provide_service_ctx.py
=> [#424] Handle empty candidates for ss

CHANGELOG.md, README.md, recommender/api/schemas/database_dump/database_dump.py, recommender/api/schemas/database_dump/provider.py, recommender/api/schemas/database_dump/research_step.py, recommender/api/schemas/database_dump/service.py, recommender/models/__init__.py, recommender/models/research_step.py, recommender/models/service.py, tests/conftest.py, tests/endpoints/conftest.py, tests/factories/marketplace/faker_seeds/research_step_names_descs.json, tests/factories/marketplace/research_step.py, tests/factories/marketplace/service.py, tests/factories/populate_database.py
closes #427 
Relevant: https://github.com/cyfronet-fid/marketplace/pull/2889
=> [#427] research steps, horizontal, pid for providers

CHANGELOG.md, recommender/tasks.py
=> [#436] omit RL training during update
